### ISSUE TITLE
%%%ZZS大佬

### ISSUE THREAD

**Issue by ZigZagK** [ZhangZisu/ZenPress#2]
大佬怎么自己写了一个博客框架啊，太强啦Orz

**Comment by thezzisu** [comment]
是的。由于Wordpress免费主题难看配置繁琐而且在低性能服务器上奇慢无比，Hexo写博客麻烦而且不支持动态功能（搜索等），到新的环境还需要clone整个项目，数学渲染又容易出锅，所以我自己写了一个博客系统。
